[colors]
background = '#0e131a'
foreground = '#fefefe'

cursor_bg = '#1a9fff'
cursor_fg = '#0e131a'
cursor_border = '#1a9fff'

selection_bg = '#23262e'
selection_fg = '#fefefe'

ansi = ['#0e131a', '#e64c49', '#72d66e', '#dbcf7b', '#3686c7', '#3887c1', '#1a9fff', '#abb2bf']
brights = ['#5c6370', '#e05f62', '#89e086', '#e8de97', '#a2d8ff', '#33839d', '#567aaa', '#ffffff']
